FROM wordpress:latest

# Ajout des paquets utiles 
RUN apt-get update && apt-get install -y sudo less mysql-client

# Ajout de WP-CLI 
RUN curl -o /bin/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
COPY wp-su.sh /bin/wp
RUN chmod +x /bin/wp-cli.phar /bin/wp

# Nettoyage
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#Ajout des datas personnalisées
ADD woocommerce-data.tar.gz /var/www/html/
RUN rm -f /var/www/html/woocommerce-data.tar.gz


