version: '2'
services:
  db:
    build: mariadb/
    image: aporaf/mariadb-blog:latest
    container_name : blog-db-test
    restart: always
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
    volumes:  
      - blog_data_db:/var/lib/mysql
      
  wordpress:
    build: wp/
    image: aporaf/blog-avec-wp-cli:latest
    container_name : blog-test
    restart: always
    links :
      - db
    ports:
      - 9200-9299:80
    volumes:
      - blog_data:/var/www/html
    depends_on:
      - db
   
volumes:
  blog_data_db: {}
  blog_data: {}
