version: '2'
services:
  db:
    build: mariadb/
    image: aporaf/mariadb-woocommerce:latest
    container_name : woocommerce-db-test
    restart: always
    expose :
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: bdAdmin
    volumes:  
      - woocommerce_data_db:/var/lib/mysql
      
  wordpress:
    build: wp/
    image: aporaf/woocommerce-avec-wp-cli:latest
    container_name : woocommerce-test
    restart: always
    links :
      - db
    ports:
      - 9200-9299:80
    volumes:
      - woocommerce_data:/var/www/html
    depends_on:
      - db
   
volumes:
  woocommerce_data_db: {}
  woocommerce_data: {}
